### ISSUE TITLE
Getting Budgie: Document openSUSE procedure

### ISSUE THREAD

**Issue by JoshStrobl** [BuddiesOfBudgie/docs#2]
Budgie Desktop is available through the [X11:Solus](https://build.opensuse.org/project/show/X11:Solus) namespace (this should really be renamed to just `BuddiesOfBudgie`) and should be documented for openSUSE users.

**Comment by JoshStrobl** [comment]
Pinging @gmbr3 about this since they maintain the packaging for OpenSUSE :)

**Comment by gmbr3** [comment]
Thanks for the ping. The X11:Solus namespace should be X11:Budgie but I don't have the permissions in the parent X11 project to be able to create it.

Budgie is available in the default repositories of openSUSE Leap (15.2+) and Tumbleweed

Budgie can be installed in the following ways:

GUI (Leap 15.4+ and Tumbleweed):
Choose the 'Budgie Desktop Environment' pattern under the 'Desktop Environments' section in YaST Software Management

CLI:
Installing the 'budgie-desktop' package through zypper
